/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendance.give.ug;
import javax.swing.*;

/**
 *
 * @author amonkats
 */
public class ViewInfoForm extends javax.swing.JFrame {

     ButtonGroup group;
     ButtonModel model;
    public JRadioButton nationality, gender;
    
    public ViewInfoForm() {
        initComponents();
        setResizable(false);
        group = new ButtonGroup();
        group.add(confirmA);
        group.add(confirmP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        att_Id = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        job = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        timeReport = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        confirmP = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        confirmA = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Reject = new javax.swing.JComboBox<>();
        depart = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        dateReport = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setPreferredSize(new java.awt.Dimension(840, 500));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.setEditable(false);
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 170, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Piscs/arms.jpg"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 220, 160));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Attendance IDNo");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 100, 30));

        att_Id.setEditable(false);
        jPanel3.add(att_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 170, 30));

        jLabel15.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Designation");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 70, 30));

        job.setEditable(false);
        jPanel3.add(job, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 170, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Piscs/flat4.jpg"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 500, 110));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee IDNo");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 90, 30));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 140, 30));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("First Name");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 70, 30));

        fname.setEditable(false);
        jPanel3.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 170, 30));

        jLabel19.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Date Reported");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, -1, 30));

        timeReport.setEditable(false);
        jPanel3.add(timeReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 170, 30));

        jLabel22.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Personal Attendance Details");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 330, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Piscs/detail.jpg"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 220, 240));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Time Reported");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 90, 30));

        confirmP.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        confirmP.setForeground(new java.awt.Color(255, 255, 255));
        confirmP.setText("Present");
        confirmP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                confirmPradioFemaleItemStateChanged(evt);
            }
        });
        confirmP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPActionPerformed(evt);
            }
        });
        jPanel3.add(confirmP, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 70, 30));

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Attendance");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 70, 30));

        confirmA.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        confirmA.setForeground(new java.awt.Color(255, 255, 255));
        confirmA.setText("Absent");
        confirmA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                confirmAItemStateChanged(evt);
            }
        });
        jPanel3.add(confirmA, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 70, 30));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 70, 30));

        lname.setEditable(false);
        jPanel3.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 170, 30));

        jLabel14.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Department");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 70, 30));

        Reject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Approved", "Rejected" }));
        jPanel3.add(Reject, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 170, 30));

        depart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F&A", " " }));
        jPanel3.add(depart, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 170, 30));

        jLabel16.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Status");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 40, 30));

        dateReport.setEditable(false);
        jPanel3.add(dateReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 170, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Piscs/display.jpg"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 980, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
        //      this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void confirmPradioFemaleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_confirmPradioFemaleItemStateChanged

        //group.setSelected(model, true);
//        ButtonModel model = group.setSelected(m, true);
        
//        gender = new JRadioButton("M");
//        gender = new JRadioButton("F");
//
//        nationality = new JRadioButton("Ugandan");
//        nationality = new JRadioButton("Foreigner");

    }//GEN-LAST:event_confirmPradioFemaleItemStateChanged

    private void confirmPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPActionPerformed

    }//GEN-LAST:event_confirmPActionPerformed

    private void confirmAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_confirmAItemStateChanged

        //group.setSelected(model, true);
//        gender = new JRadioButton("M");
//        gender = new JRadioButton("F");
//
//        nationality = new JRadioButton("Ugandan");
//        nationality = new JRadioButton("Foreigner");

    }//GEN-LAST:event_confirmAItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewInfoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> Reject;
    public javax.swing.JTextField att_Id;
    public javax.swing.JRadioButton confirmA;
    public javax.swing.JRadioButton confirmP;
    public javax.swing.JTextField dateReport;
    public javax.swing.JComboBox<String> depart;
    public javax.swing.JTextField fname;
    public javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JTextField job;
    public javax.swing.JTextField lname;
    public javax.swing.JTextField timeReport;
    // End of variables declaration//GEN-END:variables
}
