/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee_Register;

import javax.swing.*;
import tables.co.ug.Reg_Table;

/**
 *
 * @author amonkats
 */
public class View_Personal_Registration extends javax.swing.JFrame {

   public JRadioButton gender; 
   public JRadioButton nationality;
   ButtonGroup group, group2;
   
    public View_Personal_Registration() {
        initComponents();
        setResizable(false);
        setTitle("Ministry Of Finance Attendance Management System (MOFAMS)");
        
        group = new ButtonGroup();
        group.add(radioMale);
        group.add(radioFemale);
        
        group2 = new ButtonGroup();
        group2.add(radioUganda);
        group2.add(radioForeign);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        radioMale = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        radioForeign = new javax.swing.JRadioButton();
        radioUganda = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        job = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        depart = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setPreferredSize(new java.awt.Dimension(840, 500));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.setEditable(false);
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 170, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Piscs/arms.jpg"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 220, 160));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("First Name");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 70, 30));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 60, 30));

        fname.setEditable(false);
        jPanel3.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 170, 30));

        radioMale.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        radioMale.setForeground(new java.awt.Color(255, 255, 255));
        radioMale.setText("Male");
        radioMale.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioFemaleItemStateChanged(evt);
            }
        });
        radioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMaleActionPerformed(evt);
            }
        });
        jPanel3.add(radioMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 70, 30));

        radioFemale.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        radioFemale.setForeground(new java.awt.Color(255, 255, 255));
        radioFemale.setText("Female");
        radioFemale.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioFemaleItemStateChanged(evt);
            }
        });
        jPanel3.add(radioFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 70, 30));

        radioForeign.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        radioForeign.setForeground(new java.awt.Color(255, 255, 255));
        radioForeign.setText("Foreigner");
        radioForeign.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioFemaleItemStateChanged(evt);
            }
        });
        jPanel3.add(radioForeign, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 90, -1));

        radioUganda.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        radioUganda.setForeground(new java.awt.Color(255, 255, 255));
        radioUganda.setText("Ugandan");
        radioUganda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioFemaleItemStateChanged(evt);
            }
        });
        jPanel3.add(radioUganda, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 90, 20));

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Sex");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 40, 30));

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nationality");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 70, 20));

        jLabel14.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Status");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 50, 30));

        jLabel15.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Date of Birth");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 80, 30));

        jLabel16.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Job Title");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 60, 30));

        jLabel17.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Address");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 50, 30));

        address.setEditable(false);
        jPanel3.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, 170, 30));

        job.setEditable(false);
        jPanel3.add(job, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 170, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Piscs/flat4.jpg"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 500, 110));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee ID");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 70, 30));

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 490, 140, 30));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Last Name");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 70, 30));

        lname.setEditable(false);
        jPanel3.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 170, 30));

        jLabel19.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Department");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 70, 30));

        username.setEditable(false);
        jPanel3.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 180, 30));

        jLabel20.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("City");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 40, 30));

        mobile.setEditable(false);
        jPanel3.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, 170, 30));

        jLabel21.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Mobile_No");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 60, 30));

        jLabel22.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Personal Information");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 280, 30));

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One...", "Married", "Single" }));
        jPanel3.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 170, 30));

        jLabel23.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Email");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 60, 30));

        email.setEditable(false);
        jPanel3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, 170, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Piscs/detail.jpg"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 220, 270));

        dob.setDateFormatString("yyyy-MM-dd");
        jPanel3.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 170, 30));

        depart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One...", "Treasury", "IT", "Debt", "Human Resource", " " }));
        jPanel3.add(depart, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, 170, 30));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 60, 30));

        city.setEditable(false);
        jPanel3.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 180, 30));

        pass.setEditable(false);
        jPanel3.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 180, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Piscs/display.jpg"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 950, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMaleActionPerformed

        

    }//GEN-LAST:event_radioMaleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       
      this.dispose();
//      this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void radioFemaleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioFemaleItemStateChanged
        
//        gender = new JRadioButton("M");
//        gender = new JRadioButton("F");
//        
//        nationality = new JRadioButton("Ugandan");
//        nationality = new JRadioButton("Foreigner");
        
    }//GEN-LAST:event_radioFemaleItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Personal_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Personal_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Personal_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Personal_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Personal_Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField address;
    public javax.swing.JTextField city;
    public javax.swing.JComboBox<String> depart;
    public com.toedter.calendar.JDateChooser dob;
    public javax.swing.JTextField email;
    public javax.swing.JTextField fname;
    public javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JTextField job;
    public javax.swing.JTextField lname;
    public javax.swing.JTextField mobile;
    public javax.swing.JPasswordField pass;
    public javax.swing.JRadioButton radioFemale;
    public javax.swing.JRadioButton radioForeign;
    public javax.swing.JRadioButton radioMale;
    public javax.swing.JRadioButton radioUganda;
    public javax.swing.JComboBox<String> status;
    public javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
